import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Lightbulb, Palette, CalendarDays, BarChart3, Clock,
  CheckCircle2, AlertCircle, Megaphone, Sparkles, ArrowRight, Zap, Loader2,
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { useState } from "react";
import { HoverExplainer } from "@/components/HoverExplainer";

const widgets = [
  { title: "Concepts Ready", value: "7", desc: "Awaiting review", icon: Lightbulb, gradient: "from-violet-500/10 to-fuchsia-500/5", url: "/concepts" },
  { title: "Studio Assets", value: "21", desc: "Generated this week", icon: Palette, gradient: "from-fuchsia-500/10 to-pink-500/5", url: "/studio" },
  { title: "Calendar", value: "3", desc: "Scheduled this week", icon: CalendarDays, gradient: "from-cyan-500/10 to-teal-500/5", url: "/calendar" },
  { title: "Assets In Progress", value: "5", desc: "Currently generating", icon: Loader2, gradient: "from-amber-500/10 to-orange-500/5", url: "/studio" },
];

const widgetExplainers: Record<string, string> = {
  "Concepts Ready": "Displays count of concepts in 'pending' status across all campaigns. Clicking navigates to /concepts filtered by status=pending. Backend: query concepts table WHERE status='pending' GROUP BY campaign.",
  "Studio Assets": "Shows total assets generated in the current week. Clicking navigates to /studio. Backend: query studio_assets WHERE created_at >= start_of_week.",
  "Calendar": "Shows count of ads scheduled for this week. Clicking navigates to /calendar. Backend: query calendar_items WHERE scheduled_date BETWEEN start_of_week AND end_of_week.",
  "Assets In Progress": "Real-time count of assets currently being generated by the AI pipeline. Clicking navigates to /studio filtered by status=in_progress. Backend: query studio_assets WHERE status='generating'. Updates via WebSocket/Realtime subscription.",
};

const kpis = [
  { label: "CTR", value: "3.2%", change: "+0.4%" },
  { label: "Spend", value: "$1,240", change: "+$320" },
  { label: "ROAS", value: "4.1x", change: "+0.6x" },
  { label: "Impressions", value: "54.3K", change: "+12%" },
];

const setupHealth = [
  { label: "Brand Knowledge", done: true, url: "/brand-data-room/knowledge" },
  { label: "Products", done: true, url: "/brand-data-room/products" },
  { label: "Customer Personas", done: true, url: "/brand-data-room/personas" },
  { label: "Meta Integration", done: false, url: "/brand-data-room/meta" },
  { label: "Custom Keywords", done: false, url: "/brand-data-room/keywords" },
];

const quickActions = [
  { label: "New Campaign", icon: Megaphone, url: "/campaigns" },
  { label: "Review Concepts", icon: Lightbulb, url: "/concepts" },
  { label: "Open Studio", icon: Palette, url: "/studio" },
  { label: "View Performance", icon: BarChart3, url: "/performance" },
];

export default function Home() {
  const nav = useNavigate();
  const doneCount = setupHealth.filter((s) => s.done).length;
  const [metaConnected, setMetaConnected] = useState(true);

  return (
    <div className="space-y-8">
      {/* Hero greeting */}
      <HoverExplainer text="Hero banner: Personalized greeting using the logged-in user's first name. Dynamically generated based on auth session. Quick Actions below provide shortcuts to the most common user flows.">
        <div className="rounded-2xl gradient-home border p-6">
          <h1 className="text-3xl font-bold tracking-tight">Welcome back, John 👋</h1>
          <p className="text-muted-foreground mt-1">Here's what's happening with your brand this week.</p>
          <div className="flex flex-wrap gap-2 mt-4">
            {quickActions.map((a) => (
              <Button key={a.label} variant="outline" size="sm" className="gap-1.5 bg-card/60 backdrop-blur-sm" onClick={() => nav(a.url)}>
                <a.icon className="h-3.5 w-3.5" />
                {a.label}
              </Button>
            ))}
          </div>
        </div>
      </HoverExplainer>

      {/* Summary widgets */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {widgets.map((w) => (
          <HoverExplainer key={w.title} text={widgetExplainers[w.title]}>
            <Card className="card-hover overflow-hidden cursor-pointer" onClick={() => nav(w.url)}>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">{w.title}</CardTitle>
                <div className={`icon-badge rounded-xl bg-gradient-to-br ${w.gradient}`}>
                  <w.icon className={`h-4 w-4 text-primary ${w.title === "Assets In Progress" ? "animate-spin" : ""}`} />
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold tracking-tight">{w.value}</div>
                <p className="text-xs text-muted-foreground mt-1">{w.desc}</p>
              </CardContent>
            </Card>
          </HoverExplainer>
        ))}
      </div>

      {/* Performance snapshot */}
      <HoverExplainer text="Performance Snapshot: Pulls KPIs from the connected Meta Ad Account via Meta Marketing API. Updates every hour. Shows CTR, Spend, ROAS, Impressions for the current week. If no Meta account connected, shows upsell CTA prompting the user to connect. Toggle switches between mock data and the upsell state.">
        <Card>
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <div className="icon-badge bg-gradient-to-br from-primary/10 to-primary/5 rounded-lg">
                  <BarChart3 className="h-4 w-4 text-primary" />
                </div>
                Performance Snapshot
              </CardTitle>
              <div className="flex items-center gap-2">
                <Label htmlFor="meta-toggle" className="text-xs text-muted-foreground">Meta Ad Account</Label>
                <Switch id="meta-toggle" checked={metaConnected} onCheckedChange={setMetaConnected} />
              </div>
            </div>
          </CardHeader>
          <CardContent>
            {metaConnected ? (
              <>
                <div className="flex gap-8 flex-wrap">
                  {kpis.map((k) => (
                    <div key={k.label} className="space-y-0.5">
                      <p className="text-xs text-muted-foreground uppercase tracking-wider">{k.label}</p>
                      <p className="text-2xl font-bold tracking-tight">{k.value}</p>
                      <p className="text-xs text-success font-medium">{k.change}</p>
                    </div>
                  ))}
                </div>
                <div className="flex items-end gap-1 mt-4 h-8">
                  {[40, 55, 35, 60, 75, 50, 80, 65, 90, 70, 85, 95].map((h, i) => (
                    <div key={i} className="flex-1 rounded-sm bg-primary/15" style={{ height: `${h}%` }} />
                  ))}
                </div>
              </>
            ) : (
              <div className="relative rounded-xl border-2 border-dashed border-border p-8 text-center space-y-3">
                {/* Blurred background metrics */}
                <div className="flex gap-8 flex-wrap justify-center blur-sm opacity-40 select-none pointer-events-none">
                  {kpis.map((k) => (
                    <div key={k.label} className="space-y-0.5">
                      <p className="text-xs text-muted-foreground uppercase tracking-wider">{k.label}</p>
                      <p className="text-2xl font-bold tracking-tight">{k.value}</p>
                    </div>
                  ))}
                </div>
                {/* Overlay CTA */}
                <div className="absolute inset-0 flex flex-col items-center justify-center bg-card/80 backdrop-blur-sm rounded-xl">
                  <Sparkles className="h-8 w-8 text-primary mb-2" />
                  <p className="font-semibold text-lg">Unlock real-time performance data</p>
                  <p className="text-sm text-muted-foreground max-w-sm mt-1">Connect your Meta Ad Account to see live CTR, ROAS, spend, and impressions — updated hourly.</p>
                  <Button className="mt-4 gap-1.5 gradient-primary text-white border-0" onClick={() => nav("/brand-data-room/meta")}>
                    Connect Meta Account
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </HoverExplainer>

      <div className="grid gap-4 md:grid-cols-2">
        {/* Next run */}
        <HoverExplainer text="Next Scheduled Run: Shows the next campaign scheduled to auto-run based on the user's workflow settings. Clicking navigates to the campaign detail page. Backend: query campaigns WHERE auto_run=true AND next_run_at > NOW() ORDER BY next_run_at ASC LIMIT 1.">
          <Card className="card-hover cursor-pointer" onClick={() => nav("/campaigns/1")}>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <div className="icon-badge bg-gradient-to-br from-amber-500/10 to-orange-500/5 rounded-lg">
                  <Clock className="h-4 w-4 text-amber-600" />
                </div>
                Next Scheduled Run
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xl font-bold tracking-tight">Feb 17, 2026</p>
              <p className="text-sm text-muted-foreground">9:00 AM — Weekly Ad Sprint</p>
              <div className="mt-3 flex items-center gap-2">
                <Zap className="h-3.5 w-3.5 text-amber-500" />
                <span className="text-xs text-muted-foreground">Auto-run enabled</span>
              </div>
            </CardContent>
          </Card>
        </HoverExplainer>

        {/* Setup health */}
        <HoverExplainer text="Setup Health: Tracks completion of the Brand Data Room onboarding steps. Each item links to its respective setup page. Progress bar shows percentage complete. Backend: check for existence of records in brand_knowledge, products, personas, meta_integration, and custom_keywords tables.">
          <Card className="card-hover">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <div className="icon-badge bg-gradient-to-br from-emerald-500/10 to-green-500/5 rounded-lg">
                  <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                </div>
                Setup Health
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="mb-3">
                <div className="flex justify-between text-xs mb-1">
                  <span className="text-muted-foreground">{doneCount} of {setupHealth.length} complete</span>
                  <span className="font-medium">{Math.round((doneCount / setupHealth.length) * 100)}%</span>
                </div>
                <div className="h-2 rounded-full bg-muted overflow-hidden">
                  <div className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-green-400 transition-all" style={{ width: `${(doneCount / setupHealth.length) * 100}%` }} />
                </div>
              </div>
              <ul className="space-y-2">
                {setupHealth.map((s) => (
                  <li key={s.label} className="flex items-center gap-2 text-sm">
                    {s.done ? (
                      <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                    ) : (
                      <AlertCircle className="h-4 w-4 text-amber-500" />
                    )}
                    <span className={s.done ? "" : "text-muted-foreground"}>{s.label}</span>
                    {!s.done && (
                      <Button variant="ghost" size="sm" className="ml-auto h-6 text-[10px] gap-1 text-primary" onClick={() => nav(s.url)}>
                        Set up <ArrowRight className="h-3 w-3" />
                      </Button>
                    )}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </HoverExplainer>
      </div>
    </div>
  );
}
